version: '3.8'

services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: dockerfile
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: newsfeed
    volumes:
      - ./mysql/log:/var/log/mysql
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/disk:/disk
    networks:
      - newsfeed

networks:
  newsfeed:
    driver: bridge
